
[colors.bright]
black = "0x555753"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x4e9a06"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xc4a000"

[colors.primary]
background = "0x000000"
foreground = "0xffffff"

[font]
size = 9.5

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "F5"
mods = "Super"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;44~"
key = "Comma"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;46~"
key = "Period"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BJ"
key = "J"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BH"
key = "H"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BK"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BL"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;60~"
key = 51
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[27;5;62~"
key = 52
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B;"
key = "Semicolon"
mods = "Control"

[[keyboard.bindings]]
key = "Space"
mods = "Control|Shift"
chars = "\u001B[27;6;32~"

[mouse]
hide_when_typing = true

[window]
decorations = "none"

[keyboard]
